export const homeObjOne = {
id: 'about',
lightBg: true,
lightText: false,
lightTextDesc: false,
topLine: 'Our Mission',
headline: 'We believe that tech can and should be used to make the world a better place for all to live.',
description: 'Our passion for ending food insecurity and preventing food waste has merged with our drive to create applications that embrace and drive innovation toward social good.',
buttonLabel: 'Learn More',
imgStart: false,
img: require('../../images/world-better.svg').default,
alt: 'Food Waste FAQ',
dark: true,
primary: false,
darkText: true,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Let`s Talk Facts',
    headline: 'U.S. food waste is estimated to be 30-40% of the food supply, and Californians throw away approximately 6 million tons of food waste annually.',
    description: 'Food is the single largest category of material placed in municipal landfills and represents wasted nourishment that could have helped feed families in need.',
    buttonLabel: 'Learn More',
    imgStart: true,
    img: require('../../images/take-out-boxes.svg').default,
    alt: 'Food',
    dark: false,
    primary: true,
    darkText: false,
}

export const homeObjThree = {
    id: 'contact',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Do You Need Volunteers?',
    headline: 'Yes! All you need is a form of transportation and access to your hub during delivery hours.',
    description: 'Volunteers are greatly appreciated and there is no time-commitment.',
    buttonLabel: 'Sign Up',
    imgStart: true,
    img: require('../../images/delivery.svg').default,
    alt: 'Car',
    dark: false,
    primary: true,
    darkText: false,
    }